default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  database: storage/development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  database: storage/test.sqlite3
  timeout: 5000

production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>